
substitutions:
  name: "bp-wifi-adapter"
  slug: "bp_wifi_adapter"
  friendly_name: "Blood Pressure-WiFi Adapter"

  # Bluetooth MAC address of the blood pressure monitor (must be set by user)
  bp_monitor_mac: "FF:FF:11:1D:7B:8F"
  bp_monitor_service_uuid: "fff0"
  bp_monitor_characteristic_uuid: "fff1"

  # get secrets from secrets.yaml
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key
  ap_password: !secret ap_password

packages:
  # Standard-ish ESPHome components for all devices
  board: !include ../packages/boards/esp32_c3_supermini.yaml
  base: !include ../packages/base/base.yaml
  diagnostics: !include ../packages/base/diagnostics.yaml

  features: !include ../packages/features/bluetooth.yaml

  # This must be last because it contains debug components that should be overridden by other packages if needed
  debug: !include ../packages/base/debug.yaml

